[project]
name = "llmamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "jupyter>=1.1.1",
    "marimo>=0.13.11",
    "pydantic-ai>=0.2.9",
]
